from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('users',
         views.getData,
         name='get_users'),
     path('users/<int:pk>',
          views.getUserById,
          name='get_user_by_id'),
     path('user',
          views.getUserByUsernamePassword,
          name='get_user_by_id'),
    path('users/add',
         views.addUsers,
         name='add_users'),
     path('product/add', views.addProduct, name='add_product'),
    path('users/register',
         views.registerUser,
         name='register_user'),
    path('products',
         views.getAllProducts,
         name='get_all_products'),
    path('products/<int:pk>',
         views.getProductById,
         name='get_product_by_id'),
    path('clients/<int:client_id>/purchase-history',
         views.getPurchaseHistoryByClient,
         name='get_purchase_history_by_client'),
    path('users/<int:pk>/update',
         views.updateUser,
         name='update_user'),
    path('users/<int:pk>/delete',
         views.deleteUser,
         name='delete_user'),
    path('product/<int:pk>/delete',
         views.deleteProduct,
         name='delete_product'),
    path('products/search/name/<str:name>',
         views.getProductsByName,
         name='get_products_by_name'),
    path('products/vendor/<int:vendor>',
         views.getProductsByVendor,
         name='get_products_by_name'),
    path('products/search/quantity/<int:quantity>',
         views.getProductsByQuantity,
         name='get_products_by_quantity'),
    path('purchases/unpaid',
         views.getUnpaidPurchases,
         name='get_unpaid_purchases'),
    path('purchases/user/<int:client>',
         views.getPurchaseHistoryByClient,
         name='get_purchase_history_by_client'),
    path('purchases/date-range/<str:start_date>/<str:end_date>',
         views.getPurchasesByDate,
         name='get_purchases_by_date'),
    path('login', views.login, name='login'),
    path('products/buy',
         views.buyProduct,
         name='buy_product'),
     path('purchase_history/add', views.addToShoppingCart, name='add_to_shopping_cart')
]



