# Generated by Django 5.0.3 on 2024-05-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('specification', models.CharField(max_length=2000, verbose_name='Спецификация')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('average_rating', models.FloatField(verbose_name='Средний рейтинг')),
                ('number_of_ratings', models.PositiveIntegerField(verbose_name='Количество оценок')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BackendApp.users', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BackendApp.users', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BackendApp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История покупки',
                'verbose_name_plural': 'Истории покупок',
                'ordering': ['-created'],
            },
        ),
    ]
