# Generated by Django 5.0.3 on 2024-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_alter_users_options_users_email_alter_users_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
    ]
