# Generated by Django 5.0.3 on 2024-05-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_users_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя владельца карты')),
            ],
            options={
                'verbose_name': 'Платежная информация',
                'verbose_name_plural': 'Платежная информация',
                'ordering': ['owner_name'],
            },
        ),
        migrations.CreateModel(
            name='UsersPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BackendApp.paymentsinfo', verbose_name='Платежная информация')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BackendApp.users', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Платежная информация пользователя',
                'verbose_name_plural': 'Платежная информация пользователей',
                'ordering': ['-created'],
            },
        ),
    ]
