# Generated by Django 5.0.3 on 2024-05-28 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0005_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BackendApp.role', verbose_name='Роль'),
        ),
    ]
